/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/coupons` | `/coupons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/coupons/history` | `/coupons/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/coupons/redeem-qr` | `/coupons/redeem-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(app)'}/clubs/[clubId]` | `/clubs/[clubId]`, params: Router.UnknownInputParams & { clubId: string | number; } } | { pathname: `${'/(app)'}/coupons/[couponId]` | `/coupons/[couponId]`, params: Router.UnknownInputParams & { couponId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/coupons` | `/coupons`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/coupons/history` | `/coupons/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/coupons/redeem-qr` | `/coupons/redeem-qr`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(app)'}/clubs/[clubId]` | `/clubs/[clubId]`, params: Router.UnknownOutputParams & { clubId: string; } } | { pathname: `${'/(app)'}/coupons/[couponId]` | `/coupons/[couponId]`, params: Router.UnknownOutputParams & { couponId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/coupons${`?${string}` | `#${string}` | ''}` | `/coupons${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/coupons/history${`?${string}` | `#${string}` | ''}` | `/coupons/history${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/coupons/redeem-qr${`?${string}` | `#${string}` | ''}` | `/coupons/redeem-qr${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/coupons` | `/coupons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/coupons/history` | `/coupons/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/coupons/redeem-qr` | `/coupons/redeem-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(app)'}/clubs/${Router.SingleRoutePart<T>}` | `/clubs/${Router.SingleRoutePart<T>}` | `${'/(app)'}/coupons/${Router.SingleRoutePart<T>}` | `/coupons/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(app)'}/clubs/[clubId]` | `/clubs/[clubId]`, params: Router.UnknownInputParams & { clubId: string | number; } } | { pathname: `${'/(app)'}/coupons/[couponId]` | `/coupons/[couponId]`, params: Router.UnknownInputParams & { couponId: string | number; } };
    }
  }
}
